language: rust
rust: stable
os: linux
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - sourceline: 'ppa:fkrull/deadsnakes'
    packages:
    - python3.5
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev
    - fakeroot
    - musl-tools
  hosts:
  - example.com
  - www.example.com

cache:
- apt
- cargo
- pip

before_cache:
- rm -r $TRAVIS_BUILD_DIR/target/cov
- rm -r $TRAVIS_BUILD_DIR/target/debug

script:
- cargo build $CARGO_ARGS
- cargo test $CARGO_ARGS

jobs:
  include:
  # tests
  - rust: stable
  - rust: stable
    os: osx
  - rust: beta
  - rust: nightly
  - env:
    - FUNC_TEST=y
    install:
    - source .travis/coverage.sh && build_kcov
    - curl https://bootstrap.pypa.io/get-pip.py -o - | python3.5 - --user
    - pip3 install -r tests/requirements.txt --user
    script:
    - cargo build $CARGO_ARGS
    - cargo test $CARGO_ARGS # for coverage
    - >
      py.test --swindon-bin=$(pwd)/target/debug/swindon \
        --swindon-config=$(pwd)/tests/config.yaml.tpl \
        --swindon-replication-config=$(pwd)/tests/config-w-replication.yaml.tpl \
        -rsxX --kcov=$HOME/.local/bin/kcov $TEST_ARGS
    - bash <(curl -s https://codecov.io/bash)

  # deploy
  - stage: Publish
    env:
    - secure: "n0eOmD1J2imokgTyXv6F0ep3PvfVTI+1pGyA8y6liDz/DiU7gh0orqIYTAj7oUvrvF+DkDvYPnFiTF3Hea4BpeVZeD6cnr3yDWaqF5GOsBAzVe6quahXXbtF066nml4qti9eQAjlcePp85ZJAJ+Ro3XwMoijI4ZyHsXRTQ6Sg6pVMCje9TNzyUyXNkHrtlkBHkdLNTaJiDkV3L3DPREJGXkjqRqm/3cP4+VPaxr14YZ/iAxOSpxQabyy1AaXVYWkWfL07yvdofLJkRCmae8o8ZCdrRbiqYOZ4ICPUNiIEUuIBUKaomF+D7Abjef3vePkxhodqtzef63rLWdfDGOorjSa4o32leIjkJNTmOWMO6NsXfDge9F6QUa+auTDnml5JJzq0/Dhmi9HwgZF75NcfNgpBhC+wbjzu/9mSo+WJlWGJFa0hNtzmBOs87DZfBYFIUGanxLHA3vfeBOoGFrU4Nu3YFKD52gFGMBBe4zC/fG9hQWbiZvhSIHVx+nyJBDPGjGb7XqixCV1ttHy85bDQ7cNxpz9DtMY9ZXywJtyO7z7X3jNrPG/t5jJEyfwebNWuYV8g15snvhjqFzovaElTShS0ZW8m4eiZaVT+O8Rk6FzNSFZjE1WdyYUgFK+Wdi70KwhqyyYyRlxvAEVl/ZPd0hfE76fs4TgZH8BT96MabM="
    install: true
    script: |
      if [[ $TRAVIS_BRANCH = master && $TRAVIS_PULL_REQUEST = false ]]; then
        .travis/publish-docs.sh;
      fi

    before_deploy: |
      mkdir -p dist
      rustup target add x86_64-unknown-linux-musl
      cargo build --target=x86_64-unknown-linux-musl --release
      fakeroot sh -ecx '
        install -D target/x86_64-unknown-linux-musl/release/swindon pkg/usr/bin/swindon
        install -D target/x86_64-unknown-linux-musl/release/swindon-dev pkg/usr/bin/swindon-dev
        tar -C pkg -czf dist/swindon-static-$TRAVIS_TAG.tar.gz usr
      '
    deploy:
      provider: releases
      api_key:
        secure: "SKTy9qH9o90kdzDrTXhjVQR1qXt+ayk/8ptSvK8IqSzVj8AV1Jwe94c+KqfiXsoJnEU0jV0KUqF57cjhRUSMrtRUlLt1vteeMciGxGhjmet3ilaBy9/hIeop3kzHmkeDDhyvw+rzRt6sT6qhBQs3WXUSPf3RCqdoGk92QxH5jAeWNDxLIBAijvuHyxV6rjpw/HNrs4J6wcypKvN68OhE9MaY9UHKf2+H6755LVz/TlVFkshbTSK9ANTaWKJ5dNLhV4622tCG9lqrebv3nhdUNxDY6z2xKFGgURc2lCi4Fs268Eg1CIQ9M2QIStIF62+x8IJhAfl7WQbPTBrkI5VCOsK59QXhaA9GcmYGSo/efZoZP3xPos+4lDqNLcQhrotc9hU5zsrO9TnTt4Um0n3HupyX+cRqs6L6pUiBJiqPWWg+xZmPLVNa5KgFTUQVrVPWcBPKVn0XV4eWJQjBTVEOjd7XdL2JuqZOsEPY99IPdIDoMS9vAmxRb+aq3VffAKuv+CV5sRWpkA895O3yI5Ohc2cJ0aWsqUKnvd+TwRFqJF2+mcCRdnyGx7xgfTkR12TFTtY99IvO6OggXIX3dfTmXZKtDGNsw9ScGcYjrGRvAqiawOv3IgLjswR70NtKnyNLIqcVxbq/h7lKW+J1xMRueTJKviq624nE46n2/yePgSA="
      file: "dist/swindon-static-$TRAVIS_TAG.tar.gz"
      skip_cleanup: true
      on:
        tags: true
