os: Visual Studio 2015

artifacts:
- path: target\debug\swindon.exe
  name: debug-binary
- path: target\debug\swindon-dev.exe
  name: debug-binary

environment:
  matrix:

### MSVC Toolchains ###

  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
  # Beta 64-bit MSVC
    - channel: beta
      target: x86_64-pc-windows-msvc
  # Nightly 64-bit MSVC
    - channel: nightly
      target: x86_64-pc-windows-msvc

### GNU Toolchains ###

  # Stable 64-bit GNU
    - channel: stable
      target: x86_64-pc-windows-gnu
      MSYS_BITS: 64

### Allowed failures ###
#
matrix:
  allow_failures:
    - channel: nightly

## Install Script ##

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - if defined MSYS_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS_BITS%\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo test --verbose %cargoflags%

notifications:
- provider: Email
  to:
  - paul@colomiets.name
  subject: Swindon build status changed
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
