[package]

name = "swindon"
version = "0.1.0"
authors = ["a.popravka@smartweb.com.ua"]

[dependencies]
futures = "0.1.2"
futures-cpupool = "0.1.2"
tokio-core = { git="https://github.com/tokio-rs/tokio-core", rev="62514fc" }
quick-error = "1.1.0"
log = "0.3.6"
env_logger = "0.3.5"
rustc-serialize = "0.3.19"
tokio-service = { git = "https://github.com/tokio-rs/tokio-service" }
quire = { git="https://github.com/tailhook/rust-quire", rev="719d201" }
argparse = "0.2.1"
time = "0.1.35"
lazy_static = "0.2.1"
mime_guess = "1.8.0"
tk-sendfile = "0.2.0"

minihttp = { git = "https://github.com/popravich/minihttp", rev="c51b384" }
netbuf = "0.3.4"

[replace]
"tokio-core:0.1.0" = { git="https://github.com/tokio-rs/tokio-core", rev="62514fc" }
