[package]

name = "swindon"
version = "0.1.0"
authors = ["a.popravka@smartweb.com.ua"]

[dependencies]
futures = "0.1.6"
futures-cpupool = "0.1.2"
tokio-core = "0.1.1"
quick-error = "1.1.0"
log = "0.3.6"
env_logger = "0.3.5"
rustc-serialize = "0.3.19"
tokio-service = { git = "https://github.com/tokio-rs/tokio-service", rev="da47a93" }
quire = "0.2.0"
argparse = "0.2.1"
time = "0.1.35"
lazy_static = "0.2.1"
mime = "0.2.2"
mime_guess = "1.8.0"
tk-sendfile = "0.3.0"
tk-bufstream = "0.1.0"
minihttp = { git = "https://github.com/popravich/minihttp", rev="5d5a4dc" }
netbuf = "0.3.7"
sha1 = "0.2.0"
curl = "0.3.8"
tokio-curl = "0.1.3"
byteorder = "0.5.3"
httparse = "1.1.2"
httpbin = { git="https://github.com/tailhook/httpbin-rs", rev="afb7f68" }
slab = "0.3.0"
matches = "0.1.4"
assert_matches = "1.0.1"
string-intern = { git="https://github.com/tailhook/string-intern", rev="d7b8c24" }
rand = "0.3.14"

[replace]
"tokio-service:0.1.0" = { git="https://github.com/tokio-rs/tokio-service", rev="da47a93" }
"minihttp:0.1.0" = { git = "https://github.com/popravich/minihttp", rev="5d5a4dc" }

[[bin]]
name = "swindon"
path = "src/main.rs"

[[bin]]
name = "swindon-dev"
path = "src/main-dev.rs"
