[package]

name = "swindon"
version = "0.1.0"
authors = ["a.popravka@smartweb.com.ua"]

[dependencies]
futures = "0.1.2"
futures-cpupool = "0.1.2"
tokio-core = { git="https://github.com/tokio-rs/tokio-core", rev="62514fc" }
quick-error = "1.1.0"
log = "0.3.6"
env_logger = "0.3.5"
rustc-serialize = "0.3.19"
tokio-service = { git = "https://github.com/tokio-rs/tokio-service" }
quire = { git="https://github.com/tailhook/rust-quire", rev="719d201" }
argparse = "0.2.1"
time = "0.1.35"
lazy_static = "0.2.1"
mime = "0.2.2"
mime_guess = "1.8.0"
tk-sendfile = "0.3.0"
tk-bufstream = "0.1.0"
minihttp = { git = "https://github.com/popravich/minihttp", rev="16126a2" }
netbuf = "0.3.6"
sha1 = "0.2.0"
curl = "0.3.8"
tokio-curl = "0.1.3"
byteorder = "0.5.3"
httparse = "1.1.2"
httpbin = { git="https://github.com/tailhook/httpbin-rs", rev="ca39b37" }

[replace]
"tokio-core:0.1.0" = { git="https://github.com/tokio-rs/tokio-core", rev="62514fc" }
"tokio-service:0.1.0" = { git="https://github.com/tokio-rs/tokio-service" }
