[package]

name = "swindon"
version = "0.1.0"
authors = ["a.popravka@smartweb.com.ua"]

[dependencies]
futures = "0.1.1"
tokio-core = "0.1.0"
quick-error = "1.1.0"
log = "0.3.6"
env_logger = "0.3.5"
rustc-serialize = "0.3.19"
tokio-service = { git = "https://github.com/tokio-rs/tokio-service" }
quire = { git="https://github.com/tailhook/rust-quire", rev="f8aecc4" }
argparse = "0.2.1"

#minihttp = { git = "https://github.com/popravich/minihttp", rev="ac1f402" }
minihttp = { git = "https://github.com/tailhook/minihttp", branch="new_handler" }
