[package]

name = "swindon"
version = "0.1.0"
authors = ["a.popravka@smartweb.com.ua"]

[dependencies]
futures = "0.1.1"
tokio-core = "0.1.0"
tokio-service = { git = "https://github.com/tokio-rs/tokio-service" }

#minihttp = { git = "https://github.com/popravich/minihttp", rev="ac1f402" }
minihttp = { git = "https://github.com/tailhook/minihttp", branch="new_handler" }
