[package]

name = "swindon"
version = "0.1.0"
authors = ["a.popravka@smartweb.com.ua"]

[dependencies]
futures = "0.1.9"
futures-cpupool = "0.1.2"
tokio-core = "0.1.4"
quick-error = "1.1.0"
log = "0.3.6"
env_logger = "0.3.5"
rustc-serialize = "0.3.19"
quire = "0.2.2"
argparse = "0.2.1"
time = "0.1.35"
lazy_static = "0.2.1"
mime = "0.2.2"
mime_guess = "1.8.0"
tk-sendfile = "0.3.1"
tk-bufstream = "0.2.4"
minihttp = { git = "https://github.com/popravich/minihttp", rev="aa74775" }
netbuf = "0.3.7"
sha1 = "0.2.0"
byteorder = "0.5.3"
httparse = "1.2.1"
httpbin = { git="https://github.com/tailhook/httpbin-rs", rev="616cfdc" }
slab = "0.3.0"
matches = "0.1.4"
assert_matches = "1.0.1"
string-intern = "0.1.4"
rand = "0.3.14"
tk-pool = "0.2.3"
abstract-ns = "0.2.4"
ns-std-threaded = "0.1.0"

[replace]
"minihttp:0.1.0" = { git = "https://github.com/popravich/minihttp", rev="aa74775" }

[[bin]]
name = "swindon"
path = "src/main.rs"

[[bin]]
name = "swindon-dev"
path = "src/main-dev.rs"
